name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to docker hub
        run: docker login --username ${{secrets.DOCKER_USER}} --password "${{secrets.DOCKER_PASSWORD}}" docker.pkg.github.com
      - name: Build image
        run: docker build -t docker.pkg.github.com/nordnotor/docker-lighttpd/app:1.0.0 .
      - name: Push to docker registry
        run: docker push docker.pkg.github.com/nordnotor/docker-lighttpd/app:1.0.0
